services:
  - type: web
    name: incentivos-v2-1-node
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SELL_ACCESS_TOKEN
        sync: false
      - key: SELL_BASE_URL
        value: https://api.getbase.com
      - key: INCENTIVOS_CONFIG
        value: config/incentivos_config.json
      - key: SELL_PER_PAGE
        value: 100
      - key: SELL_TIMEOUT_S
        value: 30
      - key: PORT
        value: 8000
